name: Version
description: "Checks and updates the version of the Pull Request"

inputs:
  github-token:
    description: "GitHub Token"
    required: true
  github-user:
    description: "GitHub Actor"
    required: true
  pull-request-ref:
    description: "Pull Request Branch Ref"
    required: true

outputs:
  version:
    description: "New Version"
    value: ${{ steps.final-version.outputs.result }}

runs:
  using: composite
  steps:
    - name: Checkout Main Branch
      uses: actions/checkout@v3
      with:
        ref: main
        token: ${{ inputs.github-token }}
        fetch-depth: 0

    - name: Set GitHub Config
      id: github
      shell: bash
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "${{ inputs.github-user }}"

    - name: Get Main Version
      id: main-version
      uses: actions/github-script@v6
      with:
        result-encoding: string
        script: return require('./package.json').version

    - name: Checkout Pull Request
      uses: actions/checkout@v3
      with:
        ref: ${{ inputs.pull-request-ref }}
        token: ${{ inputs.github-token }}
        fetch-depth: 0

    - name: Get Pull Request Version
      id: pr-version
      uses: actions/github-script@v6
      with:
        result-encoding: string
        script: return require('./package.json').version

    - name: Merge Main
      if: ${{ steps.pr-version.outputs.result < steps.main-version.outputs.result }}
      id: merge-main
      shell: bash
      run: |
          git checkout main
          git status
          git checkout "{{ inputs.pull-request-ref }}"
          git merge main --no-edit
          git push
          git status

    - name: Checkout Updated Pull Request Branch
      uses: actions/checkout@v3
      with:
        ref: ${{ inputs.pull-request-ref }}
        token: ${{ inputs.github-token }}
        fetch-depth: 0

    - name: Get Updated Version
      id: new-version
      uses: actions/github-script@v6
      with:
        result-encoding: string
        script: return require('./package.json').version

    - name: Upgrade Version
      if: ${{ steps.new-version.outputs.result == steps.main-version.outputs.result }}
      uses: clockwork-marketing-uk/actions-upgrade-version@1.1.1
      with:
        github-token: ${{ inputs.github-token }}
        github-user: ${{ inputs.github-user }}
        github-ref: ${{ inputs.pull-request-ref }}

    - name: Get Final Version
      id: final-version
      uses: actions/github-script@v6
      with:
        result-encoding: string
        script: return require('./package.json').version

    - name: Show Final Version
      shell: bash
      run: echo ${{ steps.final-version.outputs.result }}


